Server blacklist and Bittensor version fix
camfairchild/bittensor pull request #1091
Opened 2023-02-09 23:56 UTC by Eugene-hu

Correctly returns unauthenticated errors due to blacklisting and updates bittensor versioning such that higher versions such (4.11.0) are permitted by design

2023-02-10 03:09 UTC, camfairchild commented on bittensor/_neuron/text/core_server/__init__.py
> +            return False, ''
```suggestion
            return False, None
```

2023-02-10 03:10 UTC, camfairchild requested changes
See: https://github.com/opentensor/bittensor/pull/1091/files#r1102231464

2023-02-10 03:10 UTC, camfairchild commented on bittensor/_neuron/text/core_server/__init__.py
> +            return True, e
Also add type hint to function 
```python
-> Tuple[bool, Optional[Exception]]
```

2023-02-10 17:10 UTC, Eugene-hu commented on bittensor/_neuron/text/core_server/__init__.py
> +            return True, e
thanks! Nice catch, let me fix that

2023-03-31 00:02 UTC, Eugene-hu commented
closes the pr in favour of #1240

2023-03-31 00:02 UTC, closed without merging