Update delegates.json
camfairchild/bittensor pull request #1201
Opened 2023-03-21 22:14 UTC by TAOVali

"5EhvL1FVkQPpMjZX4MAADcW42i3xPSF1KiCpuaxTYVr28sux": {
        "name": "TAO-Validator.com", 
        "url": "www.tao-validator.com", 
        "description": "TAO-Validator.com is a highly secure validator on the Bittensor Network. Earn up to 4% extra APY"

2023-03-21 22:37 UTC, camfairchild requested changes

2023-03-21 22:37 UTC, camfairchild commented on delegates.json
> +        "description": "TAO-Validator.com is a highly secure validator on the Bittensor Network. Earn up to 4% extra APY"
Please remove mention of APY

2023-03-21 22:42 UTC, TAOVali commented
Will do, thanks for the quick reply

From: Cameron Fairchild ***@***.***>
Sent: Tuesday, March 21, 2023 11:38 PM
To: opentensor/bittensor ***@***.***>
Cc: TAOVali ***@***.***>; Author ***@***.***>
Subject: Re: [opentensor/bittensor] Update delegates.json (PR #1201)


@camfairchild requested changes on this pull request.

________________________________

In delegates.json<https://github.com/opentensor/bittensor/pull/1201#discussion_r1144056436>:

> @@ -63,5 +63,10 @@

         "name": "Tensor.Exchange",

         "url": "www.tensor.exchange<http://www.tensor.exchange>",

         "description": "Bittensor's first community OTC exchange"

-    }

+    },

+    "5EhvL1FVkQPpMjZX4MAADcW42i3xPSF1KiCpuaxTYVr28sux": {

+        "name": "TAO-Validator.com",

+        "url": "www.tao-validator.com<http://www.tao-validator.com>",

+        "description": "TAO-Validator.com is a highly secure validator on the Bittensor Network. Earn up to 4% extra APY"

Please remove mention of APY

—
Reply to this email directly, view it on GitHub<https://github.com/opentensor/bittensor/pull/1201#pullrequestreview-1351482236>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6UX7QBTFF5XC4IAVGPL5FLW5IUS5ANCNFSM6AAAAAAWDBOK74>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2023-03-22 14:13 UTC, TAOVali commented
Hi, could you please review the new pull request? I changed APY and used what other validators are using. Please let me know if this is alright, I would like to have our name up their asap. thank you

From: Cameron Fairchild ***@***.***>
Sent: Tuesday, March 21, 2023 11:38 PM
To: opentensor/bittensor ***@***.***>
Cc: TAOVali ***@***.***>; Author ***@***.***>
Subject: Re: [opentensor/bittensor] Update delegates.json (PR #1201)


@camfairchild requested changes on this pull request.

________________________________

In delegates.json<https://github.com/opentensor/bittensor/pull/1201#discussion_r1144056436>:

> @@ -63,5 +63,10 @@

         "name": "Tensor.Exchange",

         "url": "www.tensor.exchange<http://www.tensor.exchange>",

         "description": "Bittensor's first community OTC exchange"

-    }

+    },

+    "5EhvL1FVkQPpMjZX4MAADcW42i3xPSF1KiCpuaxTYVr28sux": {

+        "name": "TAO-Validator.com",

+        "url": "www.tao-validator.com<http://www.tao-validator.com>",

+        "description": "TAO-Validator.com is a highly secure validator on the Bittensor Network. Earn up to 4% extra APY"

Please remove mention of APY

—
Reply to this email directly, view it on GitHub<https://github.com/opentensor/bittensor/pull/1201#pullrequestreview-1351482236>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6UX7QBTFF5XC4IAVGPL5FLW5IUS5ANCNFSM6AAAAAAWDBOK74>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2023-03-22 18:54 UTC, camfairchild commented
Hi, I'm not seeing any changes in this PR, nor any new PRs? I'll re-open when you amend this

2023-03-22 18:54 UTC, closed without merging

2023-03-22 19:13 UTC, camfairchild commented
Hi, I see the new PR #1203

2023-03-23 11:41 UTC, TAOVali commented
I’ve made a new PR >> 1217, could we please get this online today? Thank you!

From: Cameron Fairchild ***@***.***>
Sent: Wednesday, March 22, 2023 8:14 PM
To: opentensor/bittensor ***@***.***>
Cc: TAOVali ***@***.***>; Author ***@***.***>
Subject: Re: [opentensor/bittensor] Update delegates.json (PR #1201)


Hi, I see the new PR #1203<https://github.com/opentensor/bittensor/pull/1203>

—
Reply to this email directly, view it on GitHub<https://github.com/opentensor/bittensor/pull/1201#issuecomment-1480122644>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6UX7QCYVESG3L6XQIHWQ7DW5NFPNANCNFSM6AAAAAAWDBOK74>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>