Bit 87 coldkey encryption security
camfairchild/bittensor pull request #1251
Opened 2023-04-05 22:44 UTC by isabella618033

2023-04-21 17:34 UTC, eduardogr commented on tests/unit_tests/bittensor_tests/test_wallet.py
> +class TestWalletUpdate(unittest.TestCase):
newlines between imports and class definition?

2023-04-21 17:34 UTC, eduardogr commented on tests/integration_tests/test_cli.py
> +
extra spaces added

2023-05-01 20:54 UTC, eduardogr commented on bittensor/_keyfile/keyfile_impl.py
> +    return keyfile_data[:len('$NACL')] == b'$NACL'
does it make sense to create a variable with the '$NACL' value to not use it twice?

2023-05-01 20:54 UTC, eduardogr commented on bittensor/_keyfile/keyfile_impl.py
> +                decrypted_keyfile_data = box.decrypt(keyfile_data[len('$NACL'):])
another usage of the value where we could use the variable/constant with '$NACL'

2023-05-01 20:57 UTC, eduardogr commented on tests/unit_tests/bittensor_tests/test_wallet.py
> +from bittensor._keyfile.keyfile_impl import encrypt_keyfile_data, decrypt_keyfile_data, keyfile_data_is_encrypted, keyfile_data_is_encrypted_nacl, keyfile_data_is_encrypted_ansible
we are already importing bittensor, right? Is this needed?

2023-05-01 20:57 UTC, eduardogr approved these changes

2023-06-23 15:40 UTC, shibshib commented
This PR is pretty important but stale now, what's the status here @isabella618033 ?

2023-07-24 21:08 UTC, camfairchild commented
> This PR is pretty important but stale now, what's the status here @isabella618033 ?

Following up on this. Are we expecting to add this still?

2023-07-26 17:27 UTC, ifrit98 commented
> This PR is pretty important but stale now, what's the status here @isabella618033 ?

Bump.

2023-08-10 14:50 UTC, camfairchild requested changes

2023-08-10 14:50 UTC, camfairchild commented on bittensor/_cli/commands/update_wallet.py
> +        if config.all == False and config.wallet.get('name') == bittensor.defaults.wallet.name and not config.no_prompt:
```suggestion
        if config.get('all', d=False) == False and config.wallet.get('name') == bittensor.defaults.wallet.name and not config.no_prompt:
```

2023-08-10 14:50 UTC, camfairchild commented on bittensor/_cli/commands/update_wallet.py
> +        if config.all == True:
```suggestion
        if config.get('all', d=False) == True:
```

2023-08-25 22:22 UTC, ifrit98 commented
Migrated to: https://github.com/opentensor/bittensor/pull/1497

2023-08-25 22:22 UTC, closed without merging