feat: overview async
camfairchild/bittensor pull request #2028
Opened 2024-06-14 12:44 UTC by gus-opentensor

# Overview Async

* Removes ProcessPoolExecutor
* Coroutines for `_get_neurons_for_netuid` & `_get_de_registered_stake_for_coldkey_wallet`

2024-06-14 16:11 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +        all_stake_info_for_coldkey = subtensor.get_stake_info_for_coldkey(
should be awaited

2024-06-14 16:11 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +            return not subtensor.is_hotkey_delegate(hotkey_ss58=stake_info.hotkey_ss58)
should be awaited

2024-06-14 16:11 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +        def _filter_stake_info(stake_info: "bittensor.StakeInfo") -> bool:
should be async

2024-06-14 16:11 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +        all_neurons: List["bittensor.NeuronInfoLite"] = subtensor.neurons_lite(
should be awaited

2024-06-14 16:11 UTC, RomanCh-OT commented on bittensor/commands/overview.py
>              alerts_table = Table(show_header=True, header_style="bold magenta")
subtensor.get_total_stake_for_coldkey below should be awaited. total_coldkey_stake_from_chain is coroutine

2024-06-14 16:18 UTC, RomanCh-OT reviewed
Since github doesn't create the commends on the unmodified lines, I put it here.
The following list of methods and properties have to be awaited across the code:
- subtensor.get_total_stake_for_coldkey()
- subtensor.get_balance()
- subtensor.block
- subtensor.get_all_subnet_netuids()
- subtensor.tempo()
- subtensor.neurons_lite()
- subtensor.get_stake_info_for_coldkey()
- subtensor.is_hotkey_delegate()

After all changes the inner function `_filter_stake_info` become to async too and should be awaited.

2024-06-14 16:19 UTC, RomanCh-OT commented
also, pls check `ruff` formatting

2024-06-14 17:43 UTC, RomanCh-OT commented on bittensor/commands/overview.py
subtensor.block and subtensor.get_all_subnet_netuids() could be gathered

2024-06-14 17:43 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +                    total_balance = total_balance + await subtensor.get_balance(
line#117 has one more `subtensor.get_balance` call which have to be awaited

2024-06-14 18:56 UTC, thewhaleking commented
![Overview Command](https://github.com/opentensor/bittensor/assets/37844818/8399f969-d054-4126-a283-68314f7bd459)

I think this is a better approach.

2024-06-14 19:00 UTC, basfroman commented
> ![Overview Command](https://private-user-images.githubusercontent.com/37844818/339874867-8399f969-d054-4126-a283-68314f7bd459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzOTE4MjUsIm5iZiI6MTcxODM5MTUyNSwicGF0aCI6Ii8zNzg0NDgxOC8zMzk4NzQ4NjctODM5OWY5NjktZDA1NC00MTI2LWEyODMtNjgzMTRmN2JkNDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE4NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMzJmNjZmZDgwZWEwZTdlYjZkMWM3ZmU3YTBjNjg1YWMyNzJiYmU4ODllMTNiN2MwMTY5M2RkN2Q2MDBkYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wIdojoOh50cjMLTjr7zN0bzY8r4HjvuqbzrKMC8Ar0Q)
> 
> I think this is a better approach.

will you able to use that approach with tui? I mean won't this block tui?

2024-06-14 19:08 UTC, thewhaleking commented
> will you able to use that approach with tui? I mean won't this block tui?
Why would it block Commander?

2024-06-14 19:12 UTC, RomanCh-OT commented
> > will you able to use that approach with tui? I mean won't this block tui?
> 
> Why would it block Commander?

I'm not saying this, just asking. I like the proposed option, but due to the fact that it is a big restructuring of logic, I'm just care about it.

2024-06-17 14:16 UTC, thewhaleking commented
> I'm not saying this, just asking. I like the proposed option, but due to the fact that it is a big restructuring of logic, I'm just care about it.

It should not block Commander. The logic needs to change in a pretty substantial way anyway, so I think this is the optimal path.

2024-06-19 04:46 UTC, RomanCh-OT requested changes

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/subtensor.py
> +        hex_bytes_result = self.query_runtime_api(
`self.query_runtime_api` should be awaited

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +    async def _run(cli: "bittensor.cli", subtensor: "bittensor.subtensor"):
I would suggest replace `cli` to `self` (PEP8)

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +            subtensor.block(), subtensor.get_all_subnet_netuids()
`subtensor.block` if property (call without `()`)

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +            results = OverviewCommand._get_neurons_for_netuids(
`_get_neurons_for_netuids` is awaitable object

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +    def _map_hotkey_to_neurons(
pls add return value type annotation

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +        return (netuid, neurons)
you can remove parentheses, just `return netuid, neurons`

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +    ) -> Tuple[int, "bittensor.NeuronInfoLite"]:
function return annotation is `Tuple[int,  list["bittensor.NeuronInfoLite"]]`

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +        return await asyncio.gather(
wrap return into the list (as says in function annotation)
```python
        return list(await asyncio.gather(
            *[
                OverviewCommand._fetch_neuron_for_netuid(netuid, subtensor)
                for netuid in netuids
            ]
        ))
```

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/commands/overview.py
> +    ) -> Tuple[int, List["bittensor.NeuronInfoLite"], Optional[str]]:
nitpick: a function's return value annotation does not match its return type

2024-06-19 04:46 UTC, RomanCh-OT commented on bittensor/subtensor.py
> +    def decode_scale_bytes(self, return_type, scale_bytes, custom_rpc_type_registry):
let's move `decode_scale_bytes` function to `bittensor/commands/utils.py` or `bittensor/commands/overview.py` as a helper function

2024-06-21 13:25 UTC, thewhaleking approved these changes
Looks good man! Just make that one method a staticmethod, and you're good to go!

2024-06-21 13:25 UTC, thewhaleking commented on bittensor/commands/overview.py
`@staticmethod`

2024-06-21 15:01 UTC, merged