Async tests fix for `tests/integration_tests` directory
camfairchild/bittensor pull request #2042
Opened 2024-06-17 19:06 UTC by RomanCh-OT

Async tests fix for `tests/integration_tests` directory

2024-06-17 19:15 UTC, ibraheem-opentensor approved these changes

2024-06-17 19:22 UTC, thewhaleking requested changes
None of these coroutine tests appear to actually run. You can test it by adding `self.assertEqual(1, 2)` into any of them, and running the suite, and they will still pass.

2024-06-17 23:40 UTC, RomanCh-OT commented
> None of these coroutine tests appear to actually run. You can test it by adding `self.assertEqual(1, 2)` into any of them, and running the suite, and they will still pass.

You defenately right! We have to use `unittest.IsolatedAsyncioTestCase` instead of `unittest.TestCase` for making correct async tests based on unittest lib.

2024-06-18 01:09 UTC, RomanCh-OT commented
**Additional context:**
- real fix `tests/integration_tests/test_subtensor_integration.py` with async unittest.
- commented blocking test in `tests/integration_tests/test_cli.py` because those tests based on sync `cli.py` module. Will be fixed later.
- test_cli.py and e2e tests marked commented until commands and cli migrated. 
- `TODO: fix after commands and cli are async migrated`

2024-06-18 16:58 UTC, thewhaleking approved these changes

2024-06-18 16:59 UTC, merged