Release/7.3.0
camfairchild/bittensor pull request #2122
Opened 2024-07-11 20:25 UTC by ibraheem-opentensor

Adds:

- Liquid Alpha
- Coldkey swaps

2024-07-11 22:54 UTC, thewhaleking requested changes

2024-07-11 22:54 UTC, thewhaleking commented on scripts/install.sh
This needs to be the original.

2024-07-12 07:00 UTC, ibraheem-opentensor commented on scripts/install.sh
Updated

2024-07-12 18:46 UTC, ibraheem-opentensor commented
E2E run: https://github.com/opentensor/bittensor/actions/runs/9912614882/job/27387807905

2024-07-12 19:51 UTC, gus-opentensor approved these changes

2024-07-12 20:33 UTC, thewhaleking approved these changes

2024-07-12 21:14 UTC, merged