btcli/bt.config: various improvements
camfairchild/bittensor pull request #2223
Opened 2024-08-11 15:11 UTC by mvds00

### Bug

- You can pass any argument to code that uses `bt.config()` with default kwargs, and it will not complain. This leads to confusion on all levels (developers, devops, users).
- `bt.config()` does some special magic that kills the `required=True` feature of argparse; it will complain that the required argument is not set, even when it is set. This leads to developers implementing workarounds such as setting semi-random default values and/or additional post-argparse checks that could/should already be done in argparse. This bug seems to originate in the recursive nature of argparse as used in bittensor.
- When using `strict=True`, subparsers will wrongly complain about not recognizing arguments like `--no_prompt`

I'm not entirely sure what `bt.config` intends to do at every turn, but I think the changes described below don't make it worse.

### Description of the Change

While fixing the bugs described above, various other small (cosmetic) improvements were done. Taken from the commit message:

- implement recursive apply function for (sub^n)argparser
- use recursive apply to eliminate repeated code
- move adding standard bt.config args to separate function
- \* use recursive apply to add standard bt.config args to all parsers
- \* make strict=True the default
- eliminate redundant COMMANDS.item.name field
- remove obsolete COMMANDS looping code
- remove redundant dest= argument
- fix some comments

The changes marked * implement a functional improvement, the rest is for improved maintainability.

### Alternate Designs

Rework `bt.config`, as it is not clear what it intends to add to argparse, that already supports tons of features.

### Possible Drawbacks

People may experience code not starting anymore because they supply unknown arguments that now lead to errors due to strict checking. This is intended. Having non-functional arguments is not useful and confusing.

### Verification Process

I tested this on some bittensor code I'm writing right now, by adding a `required=True` argument and observing that the argument is now required and that the code doesn't bail out on a supposedly missing argument. I tested to see that I now cannot add `--whatevercrapinsertedhere` without argparse complaining about an unknown arg.

The CI checks further serve as a broad verification of the argparse mechanics.

### Release Notes

N/A

2024-08-13 19:02 UTC, roman-opentensor requested changes
Left a few comments.
Overall looks good!

2024-08-13 19:02 UTC, basfroman commented on bittensor/config.py
> +    def add_standard_args(parser):
To keep a consistent naming of adding arguments across the entire bittensor, pls rename`add_standard_args` to `add_args`.

2024-08-13 19:02 UTC, roman-opentensor commented on bittensor/config.py
> +            ## Set the defaults to argparse.SUPPRESS, should remove them from the namespace
Convert this to a dostring. Also, please make the function name `l_set_defaults` a little more descriptive. Example: `load_set_defaults`.
Also, add type annotation.

2024-08-13 19:02 UTC, roman-opentensor commented on bittensor/config.py
> +    def apply_to_parser_recursive(parser, callback, depth=0):
Pls add single line docstring

2024-08-14 09:01 UTC, mvds00 commented
Fixed first round of comments, for now as a separate commit. Also fixed two issues that came up in CI, as we are now seeing previously buried issues pop up due to strict checking. Some unknown `--wallet.name` issues still under investigation.

2024-08-14 16:12 UTC, roman-opentensor commented
> Fixed first round of comments, for now as a separate commit. Also fixed two issues that came up in CI, as we are now seeing previously buried issues pop up due to strict checking. Some unknown `--wallet.name` issues still under investigation.

Nice. Could you pls fix ruff. I would like to see that all checkers passed.
Thank you!

2024-08-30 12:36 UTC, thewhaleking commented
So this is definitely an improvement, but config and flags in general are changed drastically with the new btcli (soon to release fully): https://github.com/opentensor/btcli

2025-01-09 03:47 UTC, closed without merging