Feature/mvds00/test axon subprocess error checking
camfairchild/bittensor pull request #2226
Opened 2024-08-13 15:12 UTC by mvds00

### Bug

While working with the e2e tests, it appeared that the miner code did not function well, but the test never gave any indication of this. The two issues that this PR fixes are:
- the miner code is not run with NEST_ASYNCIO disabled, leading to errors generated by uvicorn, that is used by class axon of bittensor.
- `test_axon.py` doesn't check any output of the miner code.
Although the miner code gets far enough to register an axon, making the test succeed, going forward it is not practical to not have everything working flawlessly under the hood.

### Description of the Change

The subprocess to run a miner is now started with `asyncio.create_subprocess_exec` instead of `asyncio.create_subprocess_shell` so that it can be easily terminated by the test, to examine the output.
The status of the subprocess is monitored. The NEST_ASYNCIO environment variable is set to 0 to disable nest_asyncio and fix the miner.

### Alternate Designs

Rework of the test is actively worked on, this will be a separate PR on top of these commits.

### Possible Drawbacks

Not known.

### Verification Process

The test was run and with additional debugging it was observed that the miner now runs better.

### Release Notes

N/A

2024-08-14 10:19 UTC, mvds00 commented
fixed ruff formatting issue

2024-09-03 12:38 UTC, thewhaleking requested changes
Few changes. I like the idea of this test, but I really do want nest_asyncio to completely go away in the future.

2024-09-03 12:38 UTC, thewhaleking commented on tests/e2e_tests/multistep/test_axon.py
> +    if axon_process.returncode != None:
`is not` instead of `!=`

2024-09-03 12:38 UTC, thewhaleking commented on tests/e2e_tests/multistep/test_axon.py
> +    if axon_process.returncode != None:
`is not` instead of `!=`

2024-09-03 12:38 UTC, thewhaleking commented on tests/e2e_tests/multistep/test_axon.py
> +            axon_process.returncode == None
`is` instead of `==`

2024-09-03 12:38 UTC, thewhaleking commented on tests/e2e_tests/multistep/test_axon.py
> +            axon_process.returncode == None
`is` instead of `==`

2024-09-03 12:38 UTC, thewhaleking commented on tests/e2e_tests/multistep/test_axon.py
> +    if axon_process.returncode == None:
`is`

2024-09-03 12:38 UTC, thewhaleking commented on tests/e2e_tests/multistep/test_axon.py
> +        except:
Let's not do bare `except`s. Ideally, we should know what we're trying to catch, but if not, at least `except Exception as e` and log it.

2024-09-03 12:38 UTC, thewhaleking commented on tests/e2e_tests/multistep/test_axon.py
> +    if axon_process.returncode == None:
`is`

2024-09-03 12:38 UTC, thewhaleking commented on tests/e2e_tests/multistep/test_axon.py
> +        except:
bare `except`

2025-04-11 16:58 UTC, basfroman commented
No activity for over 2 weeks

2025-04-11 16:58 UTC, closed without merging