Do not throw on wrong password input
camfairchild/bittensor pull request #2237
Opened 2024-08-15 17:38 UTC by gztensor

When user inputs a wrong password to unlock the wallet, bittensor throws and all user input is lost. This PR fixes this issue.

2024-08-30 12:32 UTC, thewhaleking approved these changes

2024-09-03 03:03 UTC, camfairchild commented
Black check isn't passing on CI

2024-09-03 13:13 UTC, thewhaleking commented
> Black check isn't passing on CI

This should go away. @roman-opentensor can you update the tests for this branch to use `ruff` instead of `black`?

2024-09-03 13:47 UTC, thewhaleking requested changes

2024-09-03 13:47 UTC, thewhaleking commented on bittensor/keyfile.py
> +            print("Wrong password, try again");
Remove this semicolon

2024-09-03 13:47 UTC, thewhaleking commented on bittensor/keyfile.py
> +            if "Decryption failed. Ciphertext failed verification" in str(e):
Remove this semicolon

2025-01-08 00:01 UTC, closed without merging