removed exit sys call for ConnectionRefusedError in _get_substrate
camfairchild/bittensor pull request #2287
Opened 2024-09-05 22:55 UTC by garrett-opentensor

Removes the sys exit call when catching a ConnectionRefusedError in the _get_substrate() method of Subtensor.

2024-09-05 22:58 UTC, camfairchild approved these changes, later dismissed

2024-09-05 23:02 UTC, ibraheem-opentensor approved these changes, later dismissed

2024-09-06 02:05 UTC, roman-opentensor requested changes
pls fix ruff formatter

2024-09-06 16:30 UTC, roman-opentensor approved these changes

2024-09-06 17:47 UTC, merged