[SDK] Add `commit reveal v3` logic (python part only)
camfairchild/bittensor pull request #2484
Opened 2024-11-27 02:15 UTC by roman-opentensor

DO NOT MERGE YET

As a next step, I need to implement rust FFI with pyo3 to provide it as python package [bittensor-commit-reveal](https://github.com/opentensor/bittensor-commit-reveal)
After rust FFI ready, function `bittensor.core.extrinsics.commit_reveal.get_encrypted_commit`will be replaced to the imported one.

2024-12-12 21:27 UTC, thewhaleking requested changes
Minor changes needed

2024-12-12 21:27 UTC, thewhaleking commented on bittensor/core/async_subtensor.py
> +    ) -> Optional[bool]:
```suggestion
    ) -> bool:
```

2024-12-12 21:27 UTC, thewhaleking commented on bittensor/core/async_subtensor.py
> +            (Optional[bool]): Returns the integer value of the hyperparameter if available; otherwise, returns None.
```suggestion
            (bool): Returns the integer value of the hyperparameter if available; otherwise, returns None.
```

2024-12-12 21:27 UTC, thewhaleking commented on bittensor/core/async_subtensor.py
> +            ) > await self.weights_rate_limit(netuid):
```suggestion
            while (
                retries < max_retries
                and await self.blocks_since_last_update(netuid, uid)
                > await self.weights_rate_limit(netuid)
                and success is False
            ):
```

2024-12-12 21:31 UTC, thewhaleking submitted a review, later dismissed

2024-12-13 00:36 UTC, garrett-opentensor approved these changes

2024-12-13 00:37 UTC, merged