[Feature] [cubit] CUDA registration solver
camfairchild/bittensor pull request #868
Opened 2022-08-05 01:14 UTC by camfairchild

This PR adds a CUDA solver for the registration POW.
- Requires: [cubit](https://github.com/opentensor/cubit/)
    - see requirements for cubit
- installed as extra `pip install -e .[cubit]`
- will throw error if the user doesn't have a CUDA device and/or cubit
### New Flags
- `--cuda (default: False)` to use CUDA registration (if available)
- `--cuda.dev_id <int> (default: 0)`
- `--cuda.TPB <int, 128, 256, 512> (default: 256)`
    - the number of threads per block in the CUDA kernel
        - should be left at default or raised to 512
        - may crash the registration process if too high
            - power of 2 only
- `--cuda.update_interval <int> (default: 50_000)`
    - the number of nonces to solve between chain updates
        - can be raised or lowered.
            - having a higher value may mean less-frequent chain updates which may lead to trying to submit a solution outside of the valid solve window for that block (not efficient)

2022-08-12 18:16 UTC, shibshib commented
Tested this and overall looks good! But looks like when running using btcli run it won't use cuda to register, so these flags don't quite apply there correct?

2022-08-12 18:17 UTC, shibshib requested changes
Merge conflicts still to be fixed

2022-08-12 19:16 UTC, camfairchild commented
> Tested this and overall looks good! But looks like when running using btcli run it won't use cuda to register, so these flags don't quite apply there correct?

I'll have to add those flags.

2022-08-15 15:35 UTC, shibshib approved these changes

2022-08-15 16:28 UTC, merged