Sign responses
camfairchild/bittensor pull request #982
Opened 2022-11-08 21:44 UTC by unconst

This PR includes a PR for response message signing. 

In the proposed change the endpoint uses its key to sign the response tensors:
signature = sign( my_hotkey + str(tensor0) + str(tensor1) .. )

The receiving peer checks the signature as follows:
keypair( endpoint_hotkey ).verify( my_hotkey + str(tensor0) + str(tensor1) ..., response.signature )

The approach solves man-in-the-middle attacks. However there are potential repeat attacks here if the endpoint is not creating unique response tensors (since the adversary can remember the signatures) however this is likely intractable given the number of unique batch combinations and inputs to the endpoint.

2022-11-08 21:48 UTC, camfairchild requested changes
Add a test for this and then LGTM

2022-11-08 21:58 UTC, robertalanm approved these changes
✅

2022-11-08 23:12 UTC, Eugene-hu reviewed
Left you a few questions

2022-11-08 23:12 UTC, Eugene-hu commented on bittensor/_axon/axon_impl.py
> +                signature_messages += resp_tensor.serializeToString()
This will lead to a significant increase in network bandwidth, no? It will almost double the amount of bandwidth per message.

2022-11-08 23:12 UTC, Eugene-hu commented on bittensor/_proto/bittensor.proto
> + 	string signature = 10;
Is this built yet? Also, will this allow for backward compatibility with previous versions?

2022-11-08 23:12 UTC, Eugene-hu commented on bittensor/_axon/axon_impl.py
> +                signature_messages += resp_tensor.serializeToString()
Would it be better if the signature were the hotkey of the recipient?

2022-11-09 20:27 UTC, closed without merging

2022-11-09 20:28 UTC, unconst commented
bunk